#I @"..\get-programming-fsharp-master\packages"
#r @"FSharp.Data\lib\net40\FSharp.Data.dll"
#r @"Newtonsoft.Json\lib\net45\Newtonsoft.Json.dll"
#r @"XPlot.GoogleCharts\lib\net45\XPlot.GoogleCharts.dll"
#r @"Google.DataTable.Net.Wrapper\lib\Google.DataTable.Net.Wrapper.dll"
#r @"FSharp.Data.SqlClient\lib\net40\FSharp.Data.SqlClient.dll"
#r @"SQLProvider\lib\FSharp.Data.SqlProvider.dll"